### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by pemsley** [hgonomeg/coot#15]
"Fullscreen" seems not to work in GTK4 Coot. Is is possible to fix it - or is "fullscreen" not a thing in GTK4? Rank 6.

**Comment by hgonomeg** [comment]
# Tasks:
* [ ] Diagnoze 
* [ ] Fix
* [ ] Test

**Comment by hgonomeg** [comment]
The broader problem seems to be the following call appearing in multiple places:
```c++
widget_from_builder("main_window")
```
From what I can tell, this is no longer valid after `new-startup.cc` got introduced. 
For some reason, an empty `main_window` still continued to exist in the .ui file, dangling there as an empty object created by Gtk.Builder, causing both confusion and potentially many more bugs in many places.

I'll find and fix those erroneous calls.

For `fullscreen()`, replacing the code above with
```c++
graphics_info_t::get_main_window()
```
fixes the issue with fullscreen.
It is still buggy due to differences in layout management, but this can be resolved very easily.

**Comment by pemsley** [comment]
Ah, I see. Old code messing us up.  I like your diagnosis and remediation.

**Comment by hgonomeg** [comment]
Everything done here. Closing.
